build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"


test-job1:
  stage: test
  script:
    - echo "This job tests something, but takes more time than test-job1."
    - echo "which simulates a test that runs 20 seconds longer than test-job1"
    - "src/test/java/core/commands/CommandForTesting/TestDemoTest.java"
