version: "3.3"
services:
  haproxy:
    build:
      context: .
      dockerfile: ./docker/haproxy/Haproxy.Dockerfile
    image: localhost:5000/haproxy:latest
    command: haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg
  redis:
    image: "redis:alpine"
    hostname: "redis"
    ports: ["6379:6379"]
  rabbitmq:
    image: "rabbitmq:management-alpine"
    hostname: "rabbitmq"
    ports: ["15672:15672","5672:5672"]
  postgres:
    image: "postgres:alpine"
    hostname: "postgres"
  netty:
    build:
      context: .
      dockerfile: ./docker/netty/Netty.Dockerfile
    image: localhost:5000/netty:latest
    depends_on: ["redis","rabbitmq","postgres"]
    ports: ["8080:8080"]
  userconsumer:
    build:
      context: .
      dockerfile: ./docker/consumers/UserConsumer.Dockerfile
    image: localhost:5000/userconsumer:latest
    ports: ["8081:8081"]
    depends_on: ["redis","rabbitmq","postgres","netty"]
  questionconsumer:
    build:
      context: .
      dockerfile: ./docker/consumers/QuestionConsumer.Dockerfile
    image: localhost:5000/questionconsumer:latest
    ports: ["8082:8082"]
    depends_on: ["redis","rabbitmq","postgres","netty"]
  pollconsumer:
    build:
      context: .
      dockerfile: ./docker/consumers/PollConsumer.Dockerfile
    image: localhost:5000/pollconsumer:latest
    ports: ["8083:8083"]
    depends_on: ["redis","rabbitmq","postgres","netty"]
  notificationconsumer:
    build:
      context: .
      dockerfile: ./docker/consumers/NotificationConsumer.Dockerfile
    image: localhost:5000/notificationconsumer:latest
    ports: ["8084:8084"]
    depends_on: ["redis","rabbitmq","postgres","netty"]
  mediaconsumer:
    build:
      context: .
      dockerfile: ./docker/consumers/MediaConsumer.Dockerfile
    image: localhost:5000/mediaconsumer:latest
    ports: ["8085:8085"]
    depends_on: ["redis","rabbitmq","postgres","netty"]
  courseconsumer:
    build:
      context: .
      dockerfile: ./docker/consumers/CourseConsumer.Dockerfile
    image: localhost:5000/courseconsumer:latest
    ports: ["8086:8086"]
    depends_on: ["redis","rabbitmq","postgres","netty"]
