version: "3.3"
services:
  redis:
    image: "redis:alpine"
    hostname: "redis"
    ports: ["6379:6379"]
  rabbitmq:
    image: "rabbitmq:management-alpine"
    hostname: "rabbitmq"
    ports: ["15672:15672","5672:5672"]
  postgres:
    image: "postgres:alpine"
    hostname: "postgres"
    env_file:
      - ./.env
    ports: ["5432:5432"]